<<<<<<< HEAD
# Generated by Django 3.0 on 2021-08-20 17:59
=======
# Generated by Django 3.0 on 2021-08-20 17:35
>>>>>>> 2265ef64aac10482d10f5b698cea72796eb17c7e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
