<<<<<<< HEAD
# Generated by Django 3.0 on 2021-08-20 17:59
=======
# Generated by Django 3.0 on 2021-08-20 17:35
>>>>>>> 2265ef64aac10482d10f5b698cea72796eb17c7e

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='escriba su enunciado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
            ],
        ),
    ]
