# Generated by Django 3.0 on 2021-08-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='enunciado',
            field=models.TextField(verbose_name='Escriba su enunciado'),
        ),
    ]
