# Generated by Django 3.0 on 2021-09-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='PuntajeObtenido')),
            ],
        ),
    ]
