# Generated by Django 3.0 on 2021-08-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta_correcta',
            field=models.BooleanField(default=False, verbose_name='Marca esta casilla cuando cargues la respuesta correcta.'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuestas',
            field=models.TextField(verbose_name='Escriba su respuesta:'),
        ),
    ]
